#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("example1_Xamarin.Resource", IsApplication=true)]

namespace example1_Xamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int round_view = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int semiround_view = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int genji = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int mccree = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int pachimari = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int pingu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int reinhardt = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int rubberduck = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int soldier76 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int zenyatta = 2130903047;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int duck = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int madamada = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int mccree = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int pachimari = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int pingu = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int reinhardt = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int s76 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int zenyatta = 2131034119;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
